### ISSUE TITLE
Specify CMG IDs and group membership conditions in Google Spreadsheet

### ISSUE THREAD

**Issue by akokai** [akokai/commongroups-archived#1]
The current CMGs tab is a good start but I'd recommend creating a new worksheet with a name we'll recognize (like "groups") that is very minimal for now. For example, it could be just these headings:
- materialid of each CMG
- name – just for human-readability
- SMILES substructure pattern.

**Comment by akokai** [comment]
I've created a new spreadsheet called **CMG parameters** in the same shared Drive folder. The program looks this up by title, so the title should not change.

- The tab called **new CMGs** contains the parameters for the next batch of compound groups that I'd like to process, as a way of testing this method. Michel, could you take a moment to check that those parameters are correct? I copied them from the main CMG structural parsing spreadsheet. 
- After these are done, we can update the `last_updated` field and move those spreadsheet rows to the **all CMGs** tab. Eventually when it's just a matter of updating existing CMGs, the program will run through all of them and check dates. For now we're just managing it ourselves.

**Comment by mdedeo** [comment]
I love it. Those look good. Fred did a pass at those and they generally worked, though formatting issues kept me from importing them. I'm a little dubious about the PFOA salts, so feel free to leave that out until you're ready for some error handling.

Also, the CMG ids are being depreciated, so lets use the new 7 digit material ID from column B of this document instead of the CMGnnnnn. https://docs.google.com/spreadsheets/d/1EjZ06F6asJ7jWlKt2i_dl5QJJ8JODcKV6PBMMsJ3rlQ/edit#gid=0
